#!/usr/bin/env python
import os, sys
from time import sleep
from optparse import OptionParser
from tools.status import *

def usage():
    print("""
usage: <option> (value)

options:

    -s     payload ip
    -l     location to save payload
    -p     payload port
    -h     show this help message   
    """)

parser = OptionParser()

parser.add_option("-s", dest="host")

parser.add_option("-p",type="int", dest="port")

parser.add_option("-l", dest="path")

(options, args) = parser.parse_args()

host = options.host
port = options.port
output = str(options.path)

add = ''
if not output.endswith(".py"):
    if output.endswith("/"):
        add = "payload.py"
    else:
        add = "/payload.py"



if host == None or port == None or output == None:
    usage()
    
else:
    try:
        print_status("generating Payload . . .")
        sleep(3)
        os.system("sh ~/pandora-framework/payloads/gen.sh "+host+" "+str(port)+" "+output+add)

        print_success("payload Generating Success . . .")
        print_msg("Payload generated to '{}' ".format(output + add))
        sleep(1)
    except:
        print_error("Payload could not be generated")
